#!/usr/bin/with-contenv bash

source /assets/functions/00-container
prepare_service single
# shellcheck disable=SC2034
PROCESS_NAME="fail2ban"

if var_true "$ENABLE_FAIL2BAN" ;  then
	mkdir -p /var/log/asterisk/
	mkdir -p /var/log/fail2ban/
	touch /var/log/asterisk/full
  	touch /var/log/asterisk/freepbx_security.log

	service fail2ban start
fi

liftoff